"""Candidate Details — full candidate profile, explainable score, on-demand AI."""

import streamlit as st

from src.ai import insights
from src.ui import state
from src.ui.theme import BLUE_SOFT, GREEN, RED, match_breakdown_card, page_title, skill_pills


def _ai_block(candidate, jd, feature, label, fn, *args):
    """Render an AI feature in its own card, with caching + a regenerate
    button, so Ollama is only called when the recruiter asks and results
    persist across reruns."""
    cached = state.get_cached_ai(candidate, feature)
    with st.container(border=True):
        col1, col2 = st.columns([4, 1])
        col1.markdown(f"**{label}**")
        with col2:
            if st.button("Generate" if not cached else "Regenerate", key=f"ai_{feature}", use_container_width=True):
                with st.spinner(f"Generating {label.lower()}..."):
                    text = fn(*args)
                state.cache_ai(candidate, feature, text)
                cached = text
        if cached:
            st.markdown(cached)
        else:
            st.caption("Not generated yet — click Generate. Works with Ollama, or falls back to a rule-based version.")


def render():
    page_title("Candidate Details")

    ranked = state.get_ranked()
    jd = state.get_jd() or {}

    if not ranked:
        st.info("Rank candidates first to view their details.")
        return

    keys = [state.candidate_key(c) for c in ranked]
    names = [c.get("name", "Unknown") for c in ranked]
    selected_key = st.session_state.get("selected_candidate")

    default_index = keys.index(selected_key) if selected_key in keys else 0
    chosen_name = st.selectbox("Candidate", names, index=default_index)
    candidate = next(c for c in ranked if c.get("name") == chosen_name)
    st.session_state["selected_candidate"] = state.candidate_key(candidate)

    # --- header ---
    st.markdown(
        f"### {candidate.get('medal', '')} {candidate.get('name')} "
        f"— Rank #{candidate.get('rank')} · {candidate.get('final_score')}% match"
    )

    # --- candidate information + score breakdown ---
    c1, c2 = st.columns(2)
    with c1:
        st.markdown("#### Candidate information")
        st.write(f"**Email:** {candidate.get('email') or '—'}")
        st.write(f"**Phone:** {candidate.get('phone') or '—'}")
        st.write(f"**Experience:** {candidate.get('experience_years', 0)} years")
        st.write(f"**Education:** {candidate.get('education') or '—'}")
        st.write(f"**Certifications:** {', '.join(candidate.get('certifications', [])) or '—'}")
    with c2:
        st.markdown("#### Match breakdown")
        match_breakdown_card(
            candidate.get("final_score", 0),
            [
                ("Skills", candidate.get("skill_score", 0)),
                ("Semantic", candidate.get("semantic_score", 0)),
                ("Experience", candidate.get("experience_score", 0)),
            ],
        )

    # --- skills ---
    st.markdown("#### Skill analysis")
    st.markdown("Matching skills")
    skill_pills(candidate.get("matched_skills", []), kind="match")
    st.markdown("Missing skills")
    skill_pills(candidate.get("missing_skills", []), kind="miss")
    st.markdown("Additional skills")
    skill_pills(candidate.get("additional_skills", []), kind="extra")

    # --- explainability (deterministic, always available) ---
    st.markdown("#### Why this score")
    for reason in candidate.get("explanation", {}).get("reasons", []):
        mark = "✓" if reason["ok"] else "✗"
        color = GREEN if reason["ok"] else RED
        st.markdown(f'<span style="color:{color};font-weight:600;">{mark}</span> {reason["text"]}', unsafe_allow_html=True)

    # --- projects / companies ---
    if candidate.get("projects"):
        st.markdown("#### Projects")
        for p in candidate["projects"]:
            st.markdown(f"- {p}")
    if candidate.get("previous_companies"):
        st.markdown("#### Experience entries")
        for company in candidate["previous_companies"]:
            st.markdown(f"- {company}")

    with st.expander("Resume preview (raw text)"):
        st.text(candidate.get("raw_text", "")[:5000] or "No raw text available.")

    # --- AI insights ---
    st.divider()
    st.markdown("### AI insights")
    st.caption("Generated by Ollama when available, with deterministic fallbacks otherwise. "
               "The AI never affects the match score — that stays deterministic.")

    _ai_block(candidate, jd, "summary", "AI resume summary", insights.generate_summary, candidate)
    _ai_block(candidate, jd, "sw", "Strengths & weaknesses", insights.generate_strengths_weaknesses, candidate)
    _ai_block(candidate, jd, "rec", "Hiring recommendation", insights.generate_hiring_recommendation, candidate)
    _ai_block(candidate, jd, "explain", "AI explanation", insights.generate_explanation, candidate, candidate.get("rank"))
    _ai_block(candidate, jd, "questions", "Interview questions", insights.generate_interview_questions, candidate, jd)
    _ai_block(candidate, jd, "improve", "Resume improvement suggestions", insights.generate_resume_improvements, candidate, jd)
